class PopulateCharactersDescriptions < ActiveRecord::Migration
  def change
		# Character.find_by(name: "Bastion").update_column(:description, "Bip bip bop bowi bip !")
		# Character.find_by(name: "D.Va").update_column(:description, "Nerf this !")
		# Character.find_by(name: "Genji").update_column(:description, "Ryuu-jin no ken wo ku-ra-eh !")
		# Character.find_by(name: "Hanzo").update_column(:description, "Ryuu-ga, Wa-ga-te-ki-wo, Ku-ra-u !")
		# Character.find_by(name: "Junkrat").update_column(:description, "Start you engines !")
		# Character.find_by(name: "Lúcio").update_column(:description, "Let's break it down !")
		# Character.find_by(name: "McCree").update_column(:description, "It's high noon somwhere in the world.")
		# Character.find_by(name: "Mei").update_column(:description, "That's a world worth fighting for !")
		# Character.find_by(name: "Mercy").update_column(:description, "Heroes never die! ... for a price.")
		# Character.find_by(name: "Pharah").update_column(:description, "Justice rains from above !")
		# Character.find_by(name: "Reaper").update_column(:description, "Die, Die, DIE !")
		# Character.find_by(name: "Reinhardt").update_column(:description, "We are honor !")
		# Character.find_by(name: "Roadhog").update_column(:description, "I'm a one man apocalypse !")
		# Character.find_by(name: "Soldier:76").update_column(:description, "Young punks, get off my lawn !")
		# Character.find_by(name: "Symmetra").update_column(:description, "My teleporter is online. We move quickly.")
		# Character.find_by(name: "Torbjörn").update_column(:description, "Molten core !")
		# Character.find_by(name: "Tracer").update_column(:description, "Don't worry loves, cavalry's here !")
		# Character.find_by(name: "Widowmaker").update_column(:description, "No one can hide from my sight.")
		# Character.find_by(name: "Winston").update_column(:description, "Did someone say ... peanut butter ?")
		# Character.find_by(name: "Zarya").update_column(:description, "Fire at will !")
		# Character.find_by(name: "Zenyatta").update_column(:description, "Pass ... into the iris.")
  end
end
