class UpdateMetaCharacters < ActiveRecord::Migration
  def change
    reaper      = Character.find_by(name: "Reaper")
    tracer      = Character.find_by(name: "Tracer")
    torbjorn    = Character.find_by(name: "Torbjörn")
    mccree      = Character.find_by(name: "McCree")
    symmetra    = Character.find_by(name: "Symmetra")
    roadhog     = Character.find_by(name: "Roadhog")
    pharah      = Character.find_by(name: "Pharah")
    reinhardt   = Character.find_by(name: "Reinhardt")
    junkrat     = Character.find_by(name: "Junkrat")
    lucio       = Character.find_by(name: "Lúcio")
    zarya       = Character.find_by(name: "Zarya")
    genji       = Character.find_by(name: "Genji")
    soldier     = Character.find_by(name: "Soldier:76")
    bastion     = Character.find_by(name: "Bastion")
    dva         = Character.find_by(name: "D.Va")
    winston     = Character.find_by(name: "Winston")
    mei         = Character.find_by(name: "Mei")
    hanzo       = Character.find_by(name: "Hanzo")
    widowmaker  = Character.find_by(name: "Widowmaker")
    mercy       = Character.find_by(name: "Mercy")
    zenyatta    = Character.find_by(name: "Zenyatta")
    
    MetaCharacter.create(strong_character_id:bastion.id,      weak_character_id:mercy.id)
    MetaCharacter.create(strong_character_id:bastion.id,      weak_character_id:reinhardt.id)
    MetaCharacter.create(strong_character_id:bastion.id,      weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:dva.id,          weak_character_id:pharah.id)
    MetaCharacter.create(strong_character_id:dva.id,          weak_character_id:reinhardt.id)
    MetaCharacter.create(strong_character_id:dva.id,          weak_character_id:widowmaker.id)
    MetaCharacter.create(strong_character_id:genji.id,        weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:genji.id,        weak_character_id:mercy.id)
    MetaCharacter.create(strong_character_id:genji.id,        weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:hanzo.id,        weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:hanzo.id,        weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:hanzo.id,        weak_character_id:widowmaker.id)
    MetaCharacter.create(strong_character_id:junkrat.id,      weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:junkrat.id,      weak_character_id:mei.id)
    MetaCharacter.create(strong_character_id:junkrat.id,      weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:lucio.id,        weak_character_id:dva.id)
    MetaCharacter.create(strong_character_id:lucio.id,        weak_character_id:reaper.id)
    MetaCharacter.create(strong_character_id:lucio.id,        weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:mccree.id,       weak_character_id:reaper.id)
    MetaCharacter.create(strong_character_id:mccree.id,       weak_character_id:tracer.id)
    MetaCharacter.create(strong_character_id:mccree.id,       weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:mei.id,          weak_character_id:genji.id)
    MetaCharacter.create(strong_character_id:mei.id,          weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:mei.id,          weak_character_id:tracer.id)
    MetaCharacter.create(strong_character_id:pharah.id,       weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:pharah.id,       weak_character_id:junkrat.id)
    MetaCharacter.create(strong_character_id:pharah.id,       weak_character_id:mei.id)
    MetaCharacter.create(strong_character_id:reaper.id,       weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:reaper.id,       weak_character_id:mei.id)
    MetaCharacter.create(strong_character_id:reaper.id,       weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:reinhardt.id,    weak_character_id:soldier.id)
    MetaCharacter.create(strong_character_id:reinhardt.id,    weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:reinhardt.id,    weak_character_id:widowmaker.id)
    MetaCharacter.create(strong_character_id:roadhog.id,      weak_character_id:pharah.id)
    MetaCharacter.create(strong_character_id:roadhog.id,      weak_character_id:reinhardt.id)
    MetaCharacter.create(strong_character_id:roadhog.id,      weak_character_id:tracer.id)
    MetaCharacter.create(strong_character_id:soldier.id,      weak_character_id:mercy.id)
    MetaCharacter.create(strong_character_id:soldier.id,      weak_character_id:pharah.id)
    MetaCharacter.create(strong_character_id:soldier.id,      weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:symmetra.id,     weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:symmetra.id,     weak_character_id:dva.id)
    MetaCharacter.create(strong_character_id:symmetra.id,     weak_character_id:reinhardt.id)
    MetaCharacter.create(strong_character_id:torbjorn.id,     weak_character_id:genji.id)
    MetaCharacter.create(strong_character_id:torbjorn.id,     weak_character_id:lucio.id)
    MetaCharacter.create(strong_character_id:torbjorn.id,     weak_character_id:tracer.id)
    MetaCharacter.create(strong_character_id:tracer.id,       weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:tracer.id,       weak_character_id:mercy.id)
    MetaCharacter.create(strong_character_id:tracer.id,       weak_character_id:widowmaker.id)
    MetaCharacter.create(strong_character_id:widowmaker.id,   weak_character_id:bastion.id)
    MetaCharacter.create(strong_character_id:widowmaker.id,   weak_character_id:torbjorn.id)
    MetaCharacter.create(strong_character_id:widowmaker.id,   weak_character_id:pharah.id)
    MetaCharacter.create(strong_character_id:winston.id,      weak_character_id:genji.id)
    MetaCharacter.create(strong_character_id:winston.id,      weak_character_id:hanzo.id)
    MetaCharacter.create(strong_character_id:winston.id,      weak_character_id:widowmaker.id)
    MetaCharacter.create(strong_character_id:zarya.id,        weak_character_id:dva.id)
    MetaCharacter.create(strong_character_id:zarya.id,        weak_character_id:genji.id)
    MetaCharacter.create(strong_character_id:zarya.id,        weak_character_id:winston.id)
    MetaCharacter.create(strong_character_id:zenyatta.id,     weak_character_id:dva.id)
    MetaCharacter.create(strong_character_id:zenyatta.id,     weak_character_id:roadhog.id)
    MetaCharacter.create(strong_character_id:zenyatta.id,     weak_character_id:winston.id)
  end
end
